import {View, Text} from 'react-native';
import React from 'react';

const User = {
  id: null,
  username: null,
  mobileNo1: null,
  cardType: null,
  cardNo: null,
  cardPhoto: null,
  districtName: null,
  ifscCode: null,
  accountNo: null,
  acntType: null,
  checkbookPhoto: null,
  cityName: null,
  pincode: null,
  photo: null,
  geoLocation: null,
  totalPoints: 0,
  garageName: null,
  garageSegment: null,
  shopName: null,
  shopSegment: null,
  shopPhoto: null,
  chequeBookPhotoText: null,

  parentId: null,
  parentType: null,
  userType: null,
  mobileNo2: null,
  password: null,
  deletedFlag: null,
  statusFlag: null,
  createdOn: null,
  createdBy: null,
  lastLoggedOn: null,
  modifiedBy: null,
  modifiedOn: null,
  dob: null,
  anniversaryDate: null,
  email: null,
  companyName: null,
  companySegment: null,
  address1: null,
  address2: null,
  stateId: null,
  stateName: null,
  cityId: null,
  bankName: null,
  accountHolderName: null,
  panNo: null,
  roId: null,
  roName: null,
  aoName: null,
  apmName: null,
  longitude: null,
  latitude: null,
  addedFrom: 'APP',
  rejectedBy: null,
  rejectedOn: null,
  remarks: null,
  approvedBy: null,
  approvedOn: null,
  otp: null,
  code: null,
  errorMesage: null,
  version: null,
  points: {
    redeemed: null,
    balance: null,
    points: null,
  },
  otpType: null, //1 for Regitration 2-Login
  companyPhoto: null,
  pushNotificationToken: null,
  imagesToDelete: null, //we have to get in comma separated
  strAoId: null,
  strApmId: null,
  strDistrictId: null,
  isUpdate: false,
  activeFlag: null,
  userTypeFullName: null,
  votpFlag: null,
  customerSegment: null,
  isAccessories: null,
  monthlyTarget: null,
  isLogout: null,

  userName: null,
  userCode: null,
  userId: null,
  displayName: null,
};
export default Object.freeze(User);
